language: node_js
node_js:
  - "node"
  - "6"
before_script:
  - npm install -g istanbul
after_success:
  - npm run coveralls
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
